# Generated by Django 5.2.8 on 2025-11-29 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_quiz_question_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='num_questions',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='quiz',
            name='pdf_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='teachers.pdfnote'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(default=30, help_text='Duration in minutes'),
        ),
    ]
