# Generated by Django 5.2.8 on 2025-12-03 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_quiz_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='fullscreen_exit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='proctoring_violations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='tab_switch_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProctoringSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='proctoring/%Y/%m/%d/')),
                ('violation_type', models.CharField(max_length=50)),
                ('person_count', models.IntegerField(default=0)),
                ('phone_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='teachers.quizattempt')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
