# Generated by Django 5.2.8 on 2025-11-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_quiz_num_questions_quiz_pdf_note_alter_quiz_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Quiz deadline', null=True),
        ),
    ]
