# Generated by Django 5.2.8 on 2025-12-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_chatmessage_attached_note_chatmessage_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='topics',
            field=models.TextField(blank=True, help_text='Comma-separated topics (optional)'),
        ),
    ]
