# Generated by Django 5.2.8 on 2025-12-05 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_practicequiz_practicequizattempt'),
        ('teachers', '0009_quizattempt_fullscreen_exit_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicequiz',
            name='pdf_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_quizzes', to='teachers.pdfnote'),
        ),
        migrations.AddField(
            model_name='practicequiz',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='practice_files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='practicequiz',
            name='topic',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
