# Generated by Django 5.2.8 on 2025-12-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='semester',
        ),
    ]
